<script>
    requirejs(['jquery', 'wdph_quickview' ],
        function($, wdph_quickview) 
		{
			$(document).ready(function()
			{
				$(document).on('click', '.wdph_quickview_button', function()
				{
					var productUrl = $(this).attr('data-quickview-url');
                    if (productUrl.length)
					{
                        wdph_quickview.displayContent(productUrl);
                    }
				});
			});			
        });
	window.wdph_quickview = <?php echo \Zend_Json::encode($block->getConfig()); ?>;
</script>